name: test

on:
  pull_request:
  push:
    branches:
      - develop
      - 'releases/*'
jobs:
  test-carvel:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1 
      - uses: vmware-tanzu/carvel-setup-action@v1
      - run: |
          imgpkg version
          ytt version
          docker ps